<?php

/**
 * @file
 * leavenotice.module
 * LeaveNotice is intended to set up a site wide exit script to alert users when they are 
 * leaving the site
 */

// leavenotice global variables
define('leavenotice_url', 'http://rewdy.com/projects/view/leavenotice/');
define('leavenotice_sitename', 'my site');
define('leavenotice_css_selector', 'body');
define('leavenotice_newwindow', '');
define('leavenotice_exitmessage', '');
define('leavenotice_linkstring', '');
define('leavenotice_timeout', '');
define('leavenotice_overlayid', '');
define('leavenotice_messageboxid', '');
define('leavenotice_messageholderid', '');
define('leavenotice_overlayalpha', '');

/**
 * Implements hook_page_build().
 */
function leavenotice_page_build() {
  $path = drupal_get_path('module', 'leavenotice');
  drupal_add_css($path .'/css/jquery.leaveNotice.css', array('every_page' => TRUE));
  drupal_add_js($path .'/js/jquery.leaveNotice.min.js', array('every_page' => TRUE));
  drupal_add_js(array('leavenotice' => array(
    'selector'     => variable_get('css_selector', 'body'),
  )), 'setting');
}


/**
 * Implements hook_menu().
 */
function leavenotice_menu() {
  $items = array();
  $items['admin/settings/leavenotice'] = array(
    'title' => 'leavenotice.js',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('leavenotice_form'),
    'access arguments' => array('administer site configuration'),
  );
  return $items;
}

/**
 * Page callback for leavenotice.
 */
function leavenotice_form($form, $form_state) {
  $form = array();
  $form['leavenotice_css_selector'] = array(
    '#required' => FALSE,
    '#size' => 32,
    '#default_value' => variable_get('leavenotice_css_selector', leavenotice_css_selector),
    '#description' => t('CSS/jQuery That the leave notice will apply to. Body will get everything, but may be slow on large DOMs'),
    '#weight' => 0,
    '#type' => 'textfield',
    '#title' => t('CSS / jQuery selector'),
  );
  $form['leavenotice_exitmessage'] = array(
    '#type' => 'textarea',
    '#title' => t('This is the text you want to show in the pop-up when someone clicks on an external link. Use {SITENAME} for your site, or {URL} for the site that was clicked on.'),
    '#rows' => 3,
    '#default_value' => variable_get('leavenotice_exitmessage', '<p><strong>You have requested a website outside of {SITENAME}.</strong></p><p>Thank you for visiting.</p>'),
    '#wysiwyg' => false,
  );

  return system_settings_form($form);
}

/**
 * Implements hook_variable_info().
 */
function leavenotice_variable_info($options) {
  $variables = array();
  $variables['leavenotice_css_selector'] = array(
    'name' => 'leavenotice_css_selector',
    'title' => 'CSS selector',
    'type' => 'string',
    'default' => leavenotice_css_selector,
    'group' => 'leavenotice',
    'module' => 'leavenotice',
  );
  return $variables;
}